---
title: "Consulting Project"
output: github_document
---

# Document for Data Cleaning 

### Loading Data
```{r}
data0 <- read.csv("/Users/hannavenera/Documents/School/Pacific Lutheran University/Classes/Classes 2020-2021/Spring 2021/STAT 348/Consulting Project/share-of-calories-from-animal-protein-vs-gdp-per-capita.csv", header = TRUE)
dim(data0)
str(data0)
```

### Converting Factor Variables and Fixing Variable Names
```{r}
data1 <- data0
# changing entity to country
data1$Country <- factor(data1$Entity)
# country code
data1$Code <- factor(data1$Code)
# percent of total calories that are animal protein
data1$PercentCal <- data1$Share.of.calories.from.animal.protein..FAO..2017..
# GDP per capita
data1$GDPperCap <- data1$GDP.per.capita
# GDP
data1$GDP <- data1$GDP.per.capita*data1$Total.population..Gapminder..HYDE...UN.
# total population
data1$Pop <- data1$Total.population..Gapminder..HYDE...UN.
# redefining data
data2 <- data1[,-c(1,4,5,6,7)]
str(data2)
```

### Removing Missing Values (NA)
```{r}
data3 <- na.omit(data2)
```

### Isolating Data to Countries of Interest
```{r}
data4 <- subset(data3, Country == "Gabon" | Country == "Botswana" | Country == "Mauritius" | Country == "Kuwait" | Country == "United Arab Emirates" | Country == "Saudi Arabia" | Country == "Norway" | Country == "Switzerland" | Country == "Ireland" | Country == "United States" | Country == "Canada" | Country == "Trinidad and Tobago" | Country == "Venezuela" | Country == "Chile" | Country == "Argentina" | Country == "Hong Kong" | Country == "Taiwan" | Country == "Japan")
data4$Country <- factor(data4$Country)
table(data4$Country)
```

### Assigning a Continent to Each Measurement
```{r}
data5 <- data4
# Adding Africa
data5$Continent[data5$Country == "Botswana" | data5$Country == "Mauritius" | data5$Country == "Gabon"] <- "Africa"
# Adding Middle East
data5$Continent[data5$Country == "United Arab Emirates" | data5$Country == "Kuwait" | data5$Country == "Saudi Arabia"] <- "Middle East"
# Adding Europe
data5$Continent[data5$Country == "Ireland" | data5$Country == "Norway" | data5$Country == "Switzerland"] <- "Europe"
# Adding North America
data5$Continent[data5$Country == "United States" | data5$Country == "Canada" | data5$Country == "Trinidad and Tobago"] <- "North America"
# Adding South America
data5$Continent[data5$Country == "Argentina" | data5$Country == "Chile" | data5$Country == "Venezuela"] <- "South America"
# Adding Eastern Asia
data5$Continent[data5$Country == "Hong Kong" | data5$Country == "Taiwan" | data5$Country == "Japan"] <- "Eastern Asia"

# convert Continent to factor variable
data5$Continent <- factor(data5$Continent)
table(data5$Continent)
```

### Final Data (as of 5/1)
```{r}
FinalData <- data5
str(FinalData)
dim(FinalData)
```

